# Meta configuration of Parallel NSGA-II with tree (derivation tree) encoding

algorithm: ParallelNSGA-II
encoding: tree

metaMaxEvaluations: 2000
metaPopulationSize: 50
metaOffspringSize: 50
numberOfCores: 8

crossoverProbability: 0.9
mutationProbability: 1.0
mutationDistributionIndex: 20.0
